### PR TITLE
Use process.nextTick when available

### PR DESCRIPTION
**Pull request by maxnordlund**
This is the fastest way to schedule a new microtask in Node, running before any I/O and timers.

https://nodejs.org/api/process.html#process_process_nexttick_callback_args

### CODE REVIEW

**Comment by bluejava** [comment]
Thanks for this Max - sorry for the delay!

**Comment by maxnordlund** [comment]
No problem, let me know what you think about this.

**Comment by bluejava** [comment]
Sounds good to me. I remember reading about nextTick() - it seemed at the time it was new and unsupported in older Node still in use. Probably not true anymore...

**Comment by maxnordlund** [comment]
I've used it since node 0.8. Reading in the history section in the [docs][1], it  seems like it was added in v0.1.26. That's a while ago 😺 

[1]: https://nodejs.org/api/process.html#process_process_nexttick_callback_args

**Comment by bluejava** [comment]
Yah, reading more now.. it does seem its behavior changed in 0.9 - but thats still a long time ago.

I don't know why I avoided nextTick..  I will pull this down and do some perf testing.

Thanks again!

**Comment by maxnordlund** [comment]
Ping :)

**Comment by roblav96** [comment]
@bluejava @maxnordlund Great PR my friend! =]

Nowadays `process.nextTick` is commonly used in modern Node.js development.

**Comment by bluejava** [comment]
Finally got around to this - sorry guys. Happy to merge this change - thanks Max!

Don't expect to notice any perf improvement very often though - although `nextTick` is significantly faster than `setImmediate`, the use of this to schedule an event generally only happens once per iteration of the macro task loop - masking the performance gain. 

If you queue up a million jobs with `Zousan.soon` - they get scheduled a single time and then are executed synchronously from within Zousan internals. You have to completely exhaust this internal queue before this schedule mechanism kicks in again. And the only way to exhaust the queue and then re-queue another job is to do it outside of Zousan completely - which will also mask the performance gains UNLESS you are using the most performant scheduler as well - i.e. `nextTick`. So to see the gains, you need code like this:

```javascript
var i = 1000000

function runMeSoon()
{
	if(--i)
		process.nextTick(() => Zousan.soon(runMeSoon))
}

Zousan.soon(runMeSoon)
```

Note the calling of `Zousan.soon` from a `nextTick` call. 

Running the above code and comparing timing before/after this PR goes from 2321ms to 160ms. A nice improvement! Just don't expect to see it in actual code very often!

**Pull request closed without merging**
